from django.db import models

# Create your models here.
class Project(models.Model):
    name=models.CharField(max_length=200)
    def __str__(self):
        return self.name
class Task(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    Project =models.ForeignKey(Project, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    
class Estudiante(models.Model):
    numeroIdentificacion = models.BigIntegerField(primary_key=True)
    nombre = models.CharField(max_length=60)
    edad = models.IntegerField()
    correo = models.CharField(max_length=256, null=True, blank=True)
    estadoCivil = models.CharField(max_length=60, null=True, blank=True)
    LugarResidencia = models.CharField(max_length=400, null=True, blank=True)
    discapacidad = models.CharField(max_length=400, null=True, blank=True)
    programa = models.CharField(max_length=60, null=True, blank=True)
    telefono = models.CharField(max_length=14)
    telefonoContacto = models.CharField(max_length=14, null=True, blank=True)
    composicionFamiliar = models.CharField(max_length=400, null=True, blank=True)

class Calificaciones(models.Model):
    idCalificaciones = models.AutoField(primary_key=True)
    numeroIdentificacion = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    año = models.IntegerField()
    periodo = models.IntegerField()
    materia = models.CharField(max_length=280)
    parcial1 = models.FloatField(null=True, blank=True)
    parcial2 = models.FloatField(null=True, blank=True)
    final = models.FloatField(null=True, blank=True)
    seguimiento1 = models.FloatField(null=True, blank=True)
    seguimiento2 = models.FloatField(null=True, blank=True)
    seguimiento3 = models.FloatField(null=True, blank=True)
    seguimiento4 = models.FloatField(null=True, blank=True)

class Asesorias(models.Model):
    idAsesoria = models.AutoField(primary_key=True)
    numeroIdentificacion = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    numeroAsesoria = models.IntegerField()
    semestre = models.IntegerField()
    objetivoAsesoria = models.CharField(max_length=400)
    antecedentesPsicologicos = models.CharField(max_length=400)
    tipoApoyo = models.CharField(max_length=50)
    estadoMatricula = models.CharField(max_length=30)
    fondoSOL = models.BooleanField()
    motivoConsulta = models.CharField(max_length=400)
    fechaInicio = models.DateField()
    fechaFinal = models.DateField()
    mes = models.CharField(max_length=15)
    responsable = models.CharField(max_length=60)
    observacion = models.CharField(max_length=400, null=True, blank=True)
    riesgo = models.CharField(max_length=400, null=True, blank=True)

class Talleres(models.Model):
    idTalleres = models.AutoField(primary_key=True)
    numeroIdentificacion = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=60, null=True, blank=True)
    correo = models.CharField(max_length=256, null=True, blank=True)
    tipoVinculacion = models.CharField(max_length=60, null=True, blank=True)
    semestre = models.IntegerField(null=True, blank=True)
    programa = models.CharField(max_length=60, null=True, blank=True)
    fondoSol = models.BooleanField()
    beca = models.BooleanField()
    nombreBeca = models.CharField(max_length=280, null=True, blank=True)
    fecha = models.DateField(null=True, blank=True)
    actividad = models.CharField(max_length=400, null=True, blank=True)
    modalidad = models.CharField(max_length=20, null=True)

class AltoRiesgoDeDesercion(models.Model):
    numeroIdentificacion = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=60)
    grupo = models.CharField(max_length=280)
    codigoAsignatura = models.CharField(max_length=280)
    asignatura = models.CharField(max_length=280)
    creditos = models.IntegerField()
    asignaturaPrincipal = models.CharField(max_length=280)
    codigoAsignaturaPrincipal = models.CharField(max_length=280)
    creditosAsginaturaPrincipal = models.IntegerField()
    año = models.IntegerField()
    periodo = models.IntegerField()
    programa = models.CharField(max_length=60)
    nombreSeguimiento = models.CharField(max_length=280)
    porcentajeSeguimiento = models.FloatField()
    notaSeguimiento = models.FloatField()
    notaAcumulada = models.FloatField()
    estadoAsignatura = models.CharField(max_length=140)
    documentoDocente = models.BigIntegerField()
    nombreDocente = models.CharField(max_length=60)

class SeguimientoCienciasBasicas(models.Model):
    numeroIdentificacion = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=60)
    programa = models.CharField(max_length=60)
    creditosReprobados = models.IntegerField()
    creditosMatriculados = models.IntegerField()
    perdida = models.FloatField()
    nivel = models.IntegerField()
    retirado = models.BooleanField()
    telefono = models.CharField(max_length=14)
    correo = models.EmailField(max_length=256)
    asignaturaDifilcutad = models.CharField(max_length=60)
    responsable = models.CharField(max_length=60)
    numeroEncuentros = models.IntegerField()
    observacion = models.CharField(max_length=400)
    fecha = models.DateField()
    nivelDesercion = models.CharField(max_length=15)

class SeguimientoNivelacion(models.Model):
    numeroIdentificacion = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=True)
    estudiante = models.CharField(max_length=60)
    programa = models.CharField(max_length=60)
    creditosReprobados = models.IntegerField()
    creditosMatriculados = models.IntegerField()
    perdida = models.FloatField()
    nivel = models.IntegerField()
    retirado = models.BooleanField()
    telefono = models.CharField(max_length=14)
    correo = models.EmailField(max_length=256)
    asignaturaDifilcutad = models.CharField(max_length=60)
    responsable = models.CharField(max_length=60)
    numeroEncuentros = models.IntegerField()
    observacion = models.CharField(max_length=400)
    fecha = models.DateField()
    nivelDesercion = models.CharField(max_length=15)

class DefineTuFuturo(models.Model):
    numeroIdentificacion = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=True)
    colegio = models.CharField(max_length=200)
    fechaAplicacion = models.DateField()
    fechaDevolucion = models.DateField()
    devoluciones = models.IntegerField()
    Encargado = models.CharField(max_length=60)
    talleres = models.CharField(max_length=100)

class CharlasOV(models.Model):
    idCharlasOV = models.AutoField(primary_key=True)
    numeroIdentificacion = models.ForeignKey(Estudiante, on_delete=models.CASCADE, db_column='numeroIdentificacion')
    nombreInstitucion = models.CharField(max_length=200)
    tematica = models.CharField(max_length=60)
    fechaAplicacion = models.DateField()
    asistencia = models.IntegerField()
    dictaLaCharla = models.CharField(max_length=60)